version: "3.0"

services:
  webserver:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
    container_name: laravel_nginx
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    depends_on:
      - mysql
      - php-fpm
    networks:
      - my-network

  php-fpm:
    build:
      context: .
      dockerfile: ./Docker/php-fpm/Dockerfile
    container_name: laravel_php-fpm
    volumes:
      - ./:/var/www/html
    networks:
      - my-network

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    volumes:
      - ./Docker/data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_USER: "${DB_USERNAME}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    networks:
      - my-network

  workspace:
    build:
      context: .
      dockerfile: ./Docker/workspace/Dockerfile
    container_name: laravel_workspace
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    tty: true
    networks:
      - my-network
    depends_on:
      - mysql

networks:                             # TẠO NETWORK
  my-network:
    driver: bridge
